# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Web Qualit√©
tagline:          Journal d'un testeur
url:              http://fabrice31.github.io/blog
paginate:         3
baseurl:          /
author:
  name:           Fabrice Bournisien
  url:            https://twitter.com/fabrice31
  email:          fabrice.bournisien@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

  
pages_list:       
  About: '/about'
  Archive: '/archives'
  Feed: '/atom.xml'